AWSTemplateFormatVersion: 2010-09-09
Description: "Order 2: | Database and Subnet Groups"

Parameters:
  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  
  DBUsername:
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

Resources:
  # MySQL Database
  RelationalDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: crumbs-db
      DBSubnetGroupName: !Ref PrivateSubnetGroup
      DBName: CrumbsDatabase
      DBInstanceClass: db.t2.micro
      AllocatedStorage: '20'
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !ImportValue DatabaseSecurityGroup

  # Subnet Group
  PrivateSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: PrivateSubnetGroup
      DBSubnetGroupDescription: Subnet Group for private subnets
      SubnetIds:
        - !ImportValue PrivateSubnet1
        - !ImportValue PrivateSubnet2

Outputs:
  DatabaseEndpoint:
    Description: The database endpoint
    Value: !GetAtt RelationalDatabase.Endpoint.Address