pipeline {
  agent any
  environment {
    TF_VAR_aws_id = credentials('aws_id')
    TF_VAR_access_key = credentials('access_key')
    TF_VAR_secret_key = credentials('secret_key')
  }
  stages {
    stage('Terraform Init') {
      steps {
        sh "curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -"
        sh "sudo apt-add-repository \"deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main\""
        sudo apt install terraform
        sh "cd Terraform"
        sh "terraform init"
      }
    }
    stage('Terraform Plan') {
      steps {
        sh "terraform plan -out=tfplan"
      }
    }
    stage('Terraform Apply') {
      steps {
        input 'Apply Plan'
        sh "terraform apply -auto-approve tfplan"
      }
    }
  }
}