apiVersion: v1
kind: Namespace
metadata:
  name: dev  
  labels:
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: crumbs-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crumbs-order
  template:
    metadata:
      labels:
        app: crumbs-order
    spec:
      containers:
      - name: order-service
        image: 728482858339.dkr.ecr.us-east-1.amazonaws.com/orderservice
        ports:
        - containerPort: 8080
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: email-deployment
#   labels:
#     app: crumbs-email
# spec:
#   selector:
#     matchLabels:
#       app: crumbs-email
#   template:
#     metadata:
#       labels:
#         app: crumbs-email
#     spec:
#       containers:
#       - name: email-service
#         image: email-service
#         ports:
#         - containerPort: 8083
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  labels:
    app: crumbs-account
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crumbs-account
  template:
    metadata:
      labels:
        app: crumbs-account
    spec:
      containers:
      - name: account-service
        image: 728482858339.dkr.ecr.us-east-1.amazonaws.com/accountservice
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: restaurant-deployment    
  name: restaurant-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crumbs-restaurant
  template:
    metadata:
      labels:
        app: crumbs-restaurant
    spec:
      containers:
      - name: restaurant-deployment
        image: 728482858339.dkr.ecr.us-east-1.amazonaws.com/restaurantservice
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: order-service
  name: order-service
  namespace: dev
spec:
  selector:
    app: crumbs-order
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     run: email-service
#   name: email-service
#   namespace: dev
# spec:
#   selector:
#     app: crumbs-email
#   ports:
#   - protocol: TCP
#     port: 8083
#     targetPort: 8083
# ---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: account-service
  name: account-service
  namespace: dev
spec:
  selector:
    app: crumbs-account
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: restaurant-service
  name: restaurant-service
  namespace: dev
spec:
  selector:
    app: crumbs-restaurant
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082